# Site settings
title: Web Development Services LLC
email: webdevservicesllc@gmail.com
description: description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username: webdevservicesllc

# Build settings
markdown: kramdown
